#!/usr/bin/env python3
"""Ponto de entrada do aplicativo."""
import sys

sys.path.insert(0, "/app/share/adv-br-ui")

import gi  # noqa: E402

gi.require_version("Adw", "1")
from gi.repository import Adw  # noqa: E402

import janela  # noqa: E402


class Aplicacao(Adw.Application):
    def __init__(self):
        super().__init__(application_id="dev.lukakuuhaku.AdvBr")

    def do_activate(self):
        ativa = self.get_active_window()
        if not ativa:
            ativa = janela.Janela(self)
        ativa.present()


if __name__ == "__main__":
    sys.exit(Aplicacao().run(sys.argv))
